insightsengineering/cards

R/ard_categorical.R, R/ard_continuous.R, man/ard_categorical.Rd, man/ard_continuous.Rd, tests/testthat/_snaps/ard_categorical.md, tests/testthat/_snaps/ard_continuous.md, tests/testthat/test-ard_categorical.R, tests/testthat/test-ard_continuous.R
=> added fmt_fn argument

R/selectors.R, man/selectors.Rd, tests/testthat/test-selectors.R
**Reference GitHub issue associated with pull request.** _e.g., 'closes #1'_
closes #97 
closes #98 
=> selector updates

tests/testthat/test-ard_categorical.R, tests/testthat/test-ard_continuous.R
**Reference GitHub issue associated with pull request.** _e.g., 'closes #1'_
#96 
=> more unit tests for ARD column names

R/shuffle_ard.R
**Reference GitHub issue associated with pull request.** _e.g., 'closes #1'_
closes #113 
=> modify class check for shuffle_ard

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, DESCRIPTION
* Made updates to the contributing guide and the PR template.
**Reference GitHub issue associated with pull request.** _e.g., 'closes #1'_
closes #135 
@bzkrouse is there anything else someone should know before contributing to this project?
=> CONTRIBUTING.md

README.Rmd, README.md, inst/WORDLIST
* Added cardx refs to readme
closes #150 
=> readme update

R/ard_categorical.R, R/ard_complex.R, R/ard_continuous.R, R/ard_dichotomous.R, R/ard_hierarchical.R, R/ard_missing.R, R/get_ard_statistics.R, man/ard_categorical.Rd, man/ard_complex.Rd, man/ard_continuous.Rd, man/ard_dichotomous.Rd, man/ard_hierarchical.Rd, man/ard_missing.Rd, man/get_ard_statistics.Rd
=> adding examples to Rd files

inst/WORDLIST, vignettes/articles/structures.Rmd
=> edit vignette

README.Rmd, README.md
* Resized cardx logo in README.
Closes #162 
Updated screenshot of pkgdown site:
=> Resize cardx logo in README

_pkgdown.yml
=> Pkgdown updates

R/ard_categorical.R, R/ard_complex.R, R/ard_continuous.R, R/import-standalone-checks.R, R/process_selectors.R, man/process_selectors.Rd, tests/testthat/_snaps/process_selectors.md
=> added structural check to fns that process formula-selectors

R/shuffle_ard.R, tests/testthat/test-shuffle_ard.R
=> make sure NULL and character/logical NA are processed to be numeric NA

R/shuffle_ard.R, tests/testthat/test-shuffle_ard.R
=> shuffle trims results with length > 1

NEWS.md, R/check_pkg_installed.R, man/check_pkg_installed.Rd, tests/testthat/test-check_pkg_installed.R
* Updated `is_pkg_installed()` and `check_pkg_installed()` to allow checks for more than package at a time.
closes #201 
=> check installed updates to allow more than one pkg at a time

R/print.R, man/print.card.Rd, tests/testthat/_snaps/print.md
=> print update to use `n_col` arg for all columns

R/print_ard_conditions.R, man/print_ard_conditions.Rd
* Updated `print_ard_conditions` example to generate warnings/errors. (#230 )
Closes #230 
=> Update `print_ard_conditions` example to generate warnings/errors

R/process_selectors.R, tests/testthat/test-process_selectors.R
=> Adding deprecated note about `dplyr::vars()` as selector 

NEWS.md, R/ard_attributes.R, R/check_ard_structure.R, man/check_ard_structure.Rd, tests/testthat/_snaps/ard_attributes.md, tests/testthat/_snaps/check_ard_structure.md, tests/testthat/test-check_ard_structure.R
* Added `check_ard_structure(column_order, method)` arguments to the function to check for column ordering and whether result contains a `stat_name='method'` row.
=> Updates to the ARD checking function

R/ard_dichotomous.R, R/ard_hierarchical.R, man/ard_dichotomous.Rd, man/ard_hierarchical.Rd
* Added missing Denominators documentation section to `ard_hierarchical` and `ard_dichotomous`.
Closes #259 
=> Inherit the Denominators documentation section in all relevant functions

DESCRIPTION, inst/WORDLIST, man/cards-package.Rd
=> add gsk as author

vignettes/articles/getting-started.Rmd
=> Fixes for the AE example

DESCRIPTION, NEWS.md, R/ard_categorical.R, tests/testthat/test-ard_categorical.R
=> Update in `ard_categorical()` for some non-Base R classes

NEWS.md, R/print_ard_conditions.R, tests/testthat/_snaps/print_ard_conditions.md, tests/testthat/test-print_ard_conditions.R
=> Fix in `print_ard_conditions()` where variable not processed correctly with `cli::cli_format()`

NEWS.md, R/bind_ard.R, man/bind_ard.Rd, tests/testthat/test-bind_ard.R
* Added the `bind_ard(.quiet)` argument
closes #299
=> Added the `bind_ard(.quiet)` argument

.github/workflows/R-CMD-check.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, tests/testthat/_snaps/shuffle_ard.md, tests/testthat/test-shuffle_ard.R
=> Migrated a cardx `ard_shuffle()` test

README.Rmd, README.md
=> Adding download badge to README

README.Rmd, README.md, inst/WORDLIST
Related #338
Keep the issue open so we can add the R in Pharma links when they are available.
I think when we have more links, we can update the format to be in a cuter table and maybe use fontawesome icons to indicate video, slides, etc
=> Adding links to other resources in README

NEWS.md, R/print.R
* Updated print method for `'card'` objects so extraneous columns are never printed by default.
closes #346 
=> print method update

DESCRIPTION, tests/spelling.R
* Style this entry in a way that can be copied directly into `NEWS.md`. (#261, @kimjj93)
closes #261
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2L, repos …
```
=> fixes #261

R/ard_categorical.R, man/ard_categorical.Rd, man/ard_dichotomous.Rd
closes #381
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2L, repos = c('https://ddsjoberg.r-universe.dev', 'https://cloud.r-project.org'))"
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = …
```
=> Doc Update: Clarifying proportions vs percentages

NEWS.md, R/apply_fmt_fn.R, tests/testthat/test-apply_fmt_fn.R
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2L, repos = c('https://ddsjoberg.r-universe.dev', 'https://cloud.r-project.org'))"
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2, repos = 'https://cloud.r-project.org')"
Rscript -e …
```
=> Small update to account for a change in R-devel.

R/cards-package.R
Fixes #418
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() …
```
=> Check `devtools::build_readme()` also build `index.Rmd` ?

R/options.R, man/cards.options.Rd
Fixes #427
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() …
```
=> Update options help file
