insightsengineering/cards

.github/PULL_REQUEST_TEMPLATE.md
tests/testthat/test-ard_categorical.R

Also added a unit test for ordered factor
closes #68 
closes #15

Added PR Template 

---

R/apply_statistic_fmt_fn.R
tests/testthat/_snaps/apply_statistic_fmt_fn.md
tests/testthat/_snaps/ard_continuous.md
tests/testthat/test-apply_statistic_fmt_fn.R

* Previously, if the formatting instructions were "xx" and the rounded value was "100", a warning was printed indicating that "100" is longer than the format instruction. This warning no longer appears.

No longer warning when formatted value is longer than the `xx.x` format

---

R/ard_continuous.R
R/process_selectors.R
tests/testthat/test-process_selectors.R

* `compute_formula_selector()` now removed named elements not present in `data` argument. This update also applies to `process_formula_selectors()`. 
``` r
cards::compute_formula_selector(
data = mtcars[c("mpg", "hp")],
x = list(hp = "Present in data", not_present = "Not present in data")
)
#> $hp
#> [1] "Present in data"
```
<sup>Created on 2024-02-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
@bzkrouse FYI, I am going to merge, so I can keep working on something. If you want to discuss this change, let me know! …

`compute_formula_selector()` now removed named elements not present in `data` argument

---

R/process_selectors.R
man/process_selectors.Rd
tests/testthat/_snaps/process_selectors.md
tests/testthat/test-process_selectors.R

* This update adds as an attribute the environment associated with a pre-processed formula selector in `compute_formula_selector()` (and as a result, `process_formula_selectors()` as well). It's not uncommon that users will create the formulas in unexpected environments (which are saved with the formula), and we need access to this env during evaluation.
closes #157

Adding env to processed formulas

---

DESCRIPTION
R/tidy_as_ard.R
man/tidy_as_ard.Rd
tests/testthat/_snaps/tidy_as_ard.md
tests/testthat/test-tidy_as_ard.R

Add default to `funs_to_record` argument in `tidy_as_ard()` (#171, @ayogasekaram)
error returned when argument is omitted downstream.
closes #171 

add default to `tidy_as_ard()`

---

R/ard_attributes.R
R/ard_categorical.R
R/ard_complex.R
R/ard_continuous.R
R/ard_dichotomous.R
R/ard_hierarchical.R
R/bind_ard.R
R/import-standalone-checks.R
R/import-standalone-forcats.R
R/print_ard_conditions.R
R/shuffle_ard.R
R/summary_functions.R
R/tidy_ard_order.R
tests/testthat/_snaps/ard_continuous.md
tests/testthat/_snaps/bind_ard.md

Standalone updates

---

DESCRIPTION
NEWS.md
R/eval_capture_conditions.R
inst/WORDLIST
man/cards-package.Rd
man/eval_capture_conditions.Rd
tests/testthat/_snaps/eval_capture_conditions.md
tests/testthat/test-eval_capture_conditions.R

* Styling from the {cli} pcakage are now removed from errors and warnings when they are captured with `eval_capture_conditions()`. Styling is removed with `cli::ansi_strip()`. (#129)
closes #129 
closes #65 

Removing cli styling from errors and warnings captured with `eval_capture_conditions()`

---

NEWS.md
R/check_pkg_installed.R
tests/testthat/_snaps/check_pkg_installed.md
tests/testthat/test-check_pkg_installed.R
vignettes/articles/getting-started.Rmd

* Improved messaging in `check_pkg_installed()` that incorporates the calling function name in the case of an error. (#205)
closes #205

Improved messaging in `check_pkg_installed()`

---

NEWS.md
R/ard_stack.R
man/ard_stack.Rd
tests/testthat/test-ard_stack.R

* Updated `ard_stack()` to return `n`, `p`, and `N` for the `by` variable when specified. Previously, it only returned `N` which is the same for all levels of the by variable. (#219)
closes #219

Returning `ard_stack(by)` summary stats

---

tests/testthat/_snaps/process_selectors.md
tests/testthat/test-process_selectors.R

removing snapshot that includes error text rom dplyr

---

NEWS.md
R/ard_hierarchical.R
man/ard_hierarchical.Rd
tests/testthat/_snaps/ard_hierarchical.md
tests/testthat/test-ard_hierarchical.R

* Added the optional `ard_heirarchicial(id)` argument. When provided we check for duplicates across the column(s) supplied here. If duplicates are found, the user is warned that the percentages and denominators are not correct. (#214)
closes #214

Adding `ard_heirarchicial(id)` argument

---

.Rbuildignore
.gitlab-ci.yml

Adds a `.gitlab-ci.yml`. This shouldn't affect the package functionality. It simply enables internal automation on sync.

Create .gitlab-ci.yml for internal automations

---

NEWS.md
R/ard_stack.R
tests/testthat/_snaps/ard_stack.md
tests/testthat/test-ard_stack.R

* Bug fix where `ard_stack(by)` argument was not passed to `ard_missing()` when `ard_stack(.missing=TRUE)`. (#244)
closes #244 

Passing `ard_stack(by)` arg to `ard_missing()` when `.missing=TRUE`

---

NEWS.md
R/ard_stack.R
man/ard_stack.Rd
man/dot-eval_ard_calls.Rd
tests/testthat/_snaps/ard_stack.md
tests/testthat/test-ard_stack.R
vignettes/articles/getting-started.Rmd

* The `ard_stack(by)` argument has been renamed to `".by"` and its location moved to after the dots inputs, e.g. `ard_stack(..., .by)`. (#243)
closes #243

`ard_stack(by)` argument has been renamed to `".by"`

---

NEWS.md
R/ard_stack.R
inst/WORDLIST
tests/testthat/_snaps/ard_stack.md
tests/testthat/test-ard_stack.R

* Bug fix in `ard_stack()` when calls to functions were namespaced. (#242)
closes #242 
@bzkrouse have you come across a method for testing if a function works if the package is not loaded? That could be a good test to add too.

fix in `ard_stack()` when calls to functions were namespaced

---

R/process_selectors.R

FYI @bzkrouse, I ran into a situation in gtsummary development where `process_formula_selectors()` was being called inside some nested functions, and ran into an environment handling issue. Hopefully, we don't uncover many more of these 😬 I'll request your review when this is ready for review. I need to do some cross-package checking to ensure this solves the issue.
* Improved environment handling in `process_formula_selectors()` when formulas are utilized that include saved objects in the formula (e.g. a vector of column names).
Reviewer Checklist (if item does not apply, mark is as …

Improved environment handling in `process_formula_selectors()` for formulas

---

R/ard_stack.R
tests/testthat/_snaps/ard_stack.md
tests/testthat/test-ard_stack.R

adding better error message for `ard_stack(.by)` when mis-specified with `ard_stack(by)`

---

R/ard_complex.R

@ddsjoberg a bug was introduced when I added the code to return an empty ARD into `ard_complex()` since it needs to be done after `process_selectors()` has run. This PR reorders those two sections in the function to fix that. I noticed it when working on adding `cards::as_card()` to `cardx`.
Comes from #292 

Fix bug introduced by returning empty ARD in `ard_complex()`

---

NEWS.md
R/apply_fmt_fn.R
man/apply_fmt_fn.Rd
tests/testthat/_snaps/apply_fmt_fn.md
tests/testthat/test-apply_fmt_fn.R

* Added `apply_fmt_fn(replace)` argument. Use `replace=FALSE` to retain any previously formatted statistics in the `stat_fmt` column. (#285)
closes #285

Added `apply_fmt_fn(replace)` argument

---

NEWS.md
R/bind_ard.R
man/bind_ard.Rd
tests/testthat/_snaps/bind_ard.md
tests/testthat/test-bind_ard.R

* Added `bind_ard(.distinct)` argument, which can remove non-distinct rows from the ARD across grouping variables, primary variables, context, statistic name and value. (#286)
closes #286 

Added `bind_ard(.distinct)` argument

---

NEWS.md
R/print_ard_conditions.R
tests/testthat/_snaps/print_ard_conditions.md
tests/testthat/test-print_ard_conditions.R

* Bug fix in `print_ard_conditions()` and we can now print condition messages that contain curly brace pairs. (#309)
closes #309

Bug fix in `print_ard_conditions()` when message had curly brace pairs

---

NEWS.md
R/ard_stack.R
man/ard_stack.Rd
tests/testthat/test-ard_stack.R

* Any rows with `NA` or `NaN` values in the `.by` columns specified in `ard_stack()` are now removed from all calculations. (#320)
closes #320 

Removing NA `ard_stack(.by)` values from calculations

---

NEWS.md
R/shift_ard_columns.R
man/rename_ard_columns.Rd
tests/testthat/_snaps/rename_ard_columns.md
tests/testthat/test-rename_ard_columns.R

* Added `rename_ard_columns(unlist)` argument, which unlists specified columns in the ARD data frame. (#313)
closes #313
closes #312

Adding `rename_ard_columns(unlist)` argument

---

NEWS.md
R/ard_attributes.R
tests/testthat/_snaps/ard_attributes.md
tests/testthat/_snaps/mock.md
tests/testthat/_snaps/print.md
tests/testthat/test-ard_attributes.R

* Add columns `fmt_fn`, `warning`, and `errors` to `ard_attributes()` output (#327)
closes #327
Please let me know if there is anything else to change here. I'm not 100% sure I'm setting the `fmt_fn` column right? Also had a look at the docs for `ard_attributes()` to see if any changes were required but they only talk about the added attributes, don't mention the columns of the output.

Add columns `fmt_fn`, `warning`, and `errors` to `ard_attributes` output

---

NEWS.md
R/print_ard_conditions.R

* Improved messaging in `print_ard_conditions()` when the calling function is namespaced. (#348)
closes #348

Improved msg in `print_ard_conditions()` when the calling function is namedspaced

---

R/ard_categorical.R
R/print.R
man/ard_categorical.Rd
man/ard_dichotomous.Rd
man/dot-calculate_tabulation_statistics.Rd
man/dot-process_denominator.Rd
tests/testthat/test-ard_hierarchical.R
tests/testthat/test-tidy_ard_column_order.R

* Update phrasing for `by` and `strata` arguments (#325 )
Went with the phrasing I suggested in #325, let me know what you think - happy to brainstorm a little more if it's still not what we're after
closes #325 

Update  awkward by/strata phrasing

---

NEWS.md
R/print_ard_conditions.R
man/dot-cli_condition_messaging.Rd
man/print_ard_conditions.Rd
tests/testthat/_snaps/print_ard_conditions.md
tests/testthat/test-print_ard_conditions.R

* Added the `print_ard_conditions(condition_type)` argument, which allows users to select to return conditions as messages (the default), or have warnings returned as warnings and errors as errors. (#386)
closes #386
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = …
```

Adde `print_ard_conditions(condition_type)` argument

---

NEWS.md
R/utils.R
tests/testthat/test-nest_for_ard.R

* Fixed sorting order of logical variables in `nest_for_ard()`. (#411)
closes #411
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2L, repos = c('https://ddsjoberg.r-universe.dev', …
```

Fix in sort order in `nest_for_ard()`

---

NEWS.md
R/ard_stack_hierarchical.R
R/sort_ard_hierarchical.R
tests/testthat/_snaps/ard_stack_hierarchical.md
tests/testthat/_snaps/filter_ard_hierarchical.md
tests/testthat/test-ard_stack_hierarchical.R

* Updated `ard_stack_hierarchical()` and `ard_stack_hierarchical_count()` to automatically sort results alphanumerically. (#423)
Required 2 additional small fixes to the sorting function:
- Including attributes as "overall results" so they are sorted last
- Accounting for ARDs by highest severity, which means the last hierarchy level is specified in `by` instead of `variables`
Closes #423 
Install `checked` with `pak::pak("Genentech/checked")` or …

Sort `ard_stack_hierarchical()` results by default

---

NEWS.md
R/ard_complex.R
R/sort_ard_hierarchical.R
man/ard_complex.Rd
tests/testthat/_snaps/ard_stack_hierarchical.md
tests/testthat/test-ard_stack_hierarchical.R
vignettes/articles/creating-ards.Rmd

* Fix bug in `sort_ard_hierarchical()` when hierarchical ARD has `overall=TRUE`.
Closes #431 
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2L, repos = c('https://ddsjoberg.r-universe.dev', 'https://cloud.r-project.org'))"
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = …
```

Fix `sort_ard_hierarchical()` bug when `overall=TRUE`

---

NEWS.md
R/ard_hierarchical.R
R/ard_stack_hierarchical.R
man/ard_stack_hierarchical.Rd
tests/testthat/test-ard_stack_hierarchical.R

closes #442 
closes #443 
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = …
```

Fix bug in ard_stack_hierarchical warning for non-unique `id`s

---

R/filter_ard_hierarchical.R
tests/testthat/test-filter_ard_hierarchical.R

* Fixed bug in `filter_ard_hierarchical()` causing some empty sections to be kept when `keep_empty=FALSE` and the ARD has no `by` variable specified.
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = parallel::detectCores() - 2L, repos = c('https://ddsjoberg.r-universe.dev', 'https://cloud.r-project.org'))" …
```

Fix bug when removing empty table sections with no `by`

---

NEWS.md
R/ard_stack.R
R/ard_stack_hierarchical.R
man/ard_stack.Rd
man/ard_stack_hierarchical.Rd
tests/testthat/test-ard_stack.R
tests/testthat/test-ard_stack_hierarchical.R

closes #335 
```shell
Rscript -e "options(checked.check_envvars = c(NOT_CRAN = TRUE)); checked::check_rev_deps(path = '.', n = …
```

add by_stats options to stacking functions
